version: "3.7"
services:
  django_gunicorn:
    volumes:
      - static:/static
      - upload:/upload
  

    build:
      context: .
    ports:
      - "8005:8000"

  
   


  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data


