# Generated by Django 3.2.6 on 2021-08-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='counterModel',
        ),
        migrations.DeleteModel(
            name='loginModel',
        ),
    ]
