# Generated by Django 3.2.6 on 2021-08-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_auto_20210815_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super_AdminAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='First Name', max_length=255)),
                ('qr_code', models.ImageField(default='SuperAdmin/dummy.jpg', upload_to='SuperAdmin/')),
            ],
        ),
    ]
